# Generated by Django 4.0.3 on 2022-08-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_are_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='last_checked_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.message'),
        ),
    ]
