# Generated by Django 4.0.3 on 2022-07-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
