# Generated by Django 4.0.3 on 2022-09-15 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('O', 'Output'), ('I', 'Input')], max_length=1)),
                ('wallet_amount', models.BigIntegerField()),
                ('coins_amount', models.BigIntegerField()),
                ('perform_time', models.DateTimeField(auto_now_add=True)),
                ('blockchain_address', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
