# Generated by Django 4.0.3 on 2022-06-02 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0003_chat_are_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('bank', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='chats.chat')),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_contracts', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_contracts', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalFundsRequest',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chats.message')),
                ('first_user_agree', models.BooleanField(default=False)),
                ('second_user_agree', models.BooleanField(default=False)),
                ('moderator_agree', models.BooleanField(default=False)),
                ('first_user_funds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('second_user_funds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moderator_funds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('close_contract', models.BooleanField(default=False)),
                ('smart_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='contracts.smartcontract')),
            ],
            bases=('chats.message',),
        ),
        migrations.CreateModel(
            name='ModeratorInvite',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chats.message')),
                ('first_user_agree', models.BooleanField(default=False)),
                ('second_user_agree', models.BooleanField(default=False)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_invites', to=settings.AUTH_USER_MODEL)),
                ('smart_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_invites', to='contracts.smartcontract')),
            ],
            bases=('chats.message',),
        ),
    ]
