# Generated by Django 4.0.3 on 2022-06-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_moderatorinvite_first_user_agree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorinvite',
            name='refused',
            field=models.BooleanField(default=False),
        ),
    ]
