# Generated by Django 4.0.3 on 2022-06-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_moderatorinvite_refused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderatorinvite',
            old_name='refused',
            new_name='checked',
        ),
        migrations.AlterUniqueTogether(
            name='moderatorinvite',
            unique_together=set(),
        ),
    ]
