# Generated by Django 4.0.3 on 2022-09-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_rename_refused_moderatorinvite_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='bank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawalfundsrequest',
            name='first_user_funds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawalfundsrequest',
            name='moderator_funds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawalfundsrequest',
            name='second_user_funds',
            field=models.BigIntegerField(default=0),
        ),
    ]
